// Embeds the skill's markdown (SKILL.md + reference rulebooks) into a generated
// TS module so the browser build can use it as system context without a server
// to read files at runtime. The skill folder stays the single source of truth —
// this runs on predev/prebuild, so editing the markdown regenerates the module.
//
// This is also the seam Module A (phase 2) plugs into: machine-extracted
// obligations are written as rulebooks in the same folder and shape, so the
// auditor consumes them exactly like the hand-written ones.
import { readFile, writeFile, mkdir } from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const SKILL_ROOT = path.join(ROOT, 'skill', 'regspine-audit');

// Order matters only for readability of the assembled prompt.
const REFERENCE_FILES = [
  'dark-patterns.md', // always-on checklist — first so it's front of mind
  'securities-journey.md', // RegSpine's primary rulebook (SEBI investor protection)
  'loan-journey.md',
  'insurance-journey.md',
  'consent-dpdp.md',
  'grievance-journey.md',
  'output-formats.md',
];

const skillMd = await readFile(path.join(SKILL_ROOT, 'SKILL.md'), 'utf8');
const references = [];
for (const name of REFERENCE_FILES) {
  const content = await readFile(path.join(SKILL_ROOT, 'references', name), 'utf8');
  references.push({ name, content });
}

const out = `// AUTO-GENERATED by scripts/embed-skill.mjs — do not edit by hand.
// Source of truth: skill/regspine-audit/. Regenerated on predev/prebuild.
import type { SkillContext } from './prompt';

export const SKILL_CONTEXT: SkillContext = ${JSON.stringify(
  { skillMd, references },
  null,
  2
)};
`;

await mkdir(path.join(ROOT, 'lib'), { recursive: true });
await writeFile(path.join(ROOT, 'lib', 'skill-content.ts'), out, 'utf8');
console.log(
  `embed-skill: wrote lib/skill-content.ts (SKILL.md + ${references.length} rulebooks)`
);
